### ISSUE TITLE
Install on UX333FA

### ISSUE THREAD

**Issue by ethermcman** [FlasHRender/Zenbook-S-UX391UA-hackintosh#1]
Hi,
I've seen your posts on tonymac. 
I wonder if you can help me a little bit on perfecting my current Catalina installation. 
So far and mostly based on your repo, I have an almost working Hackintosh except Wi-Fi, sound, keyboard mapping and keyboard backlight. 
I have no DSDT.aml like you but I've managed to get it work with dortania guide and parts of your Config.plist. 
Anyway, thanks if you can help me.

**Comment by thalatamsainath** [comment]
Hey,
I don't know how useful this is now, but I have updated all APCI patches to be modular. So it would be easier for people with different models to try and boot into system.
